---
version: '2.1'
services:
  db:
    image: 'postgres:9.5.4'
    restart: always
    environment:
      POSTGRES_PASSWORD: &db_pass ${DB_PASSWORD}
      POSTGRES_USER: &db_user ${DB_USER}
      POSTGRES_DB: &db_name ${DB_NAME}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    hostname: db
    ports:
      - "5432:5432"
    networks:
      integration_network:
        aliases:
          - &db_host db
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD-SHELL"
        - "pg_isready --dbname=${DB_NAME} --host=localhost --username=${DB_USER}" 
  broker:
    image: 'rabbitmq:3.5.7-management'
    restart: always
    volumes:
      - broker_data:/var/lib/rabbitmq
    ports:
      - '15673:15672'
      - '5672:5672'
    networks:
      integration_network:
        aliases:
          - &broker_host broker
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"

networks:
  integration_network:

volumes:
  db_data:
  broker_data:
